### ISSUE TITLE
it's bull shit not sdk or api

### ISSUE THREAD

**Issue by A1Gard** [GapAfzar/Node-Gap-SDP-API#4]
سلام

واقعا مایه آبرو ریزی این مزخرفی که بعنوان 
api
دادید

لایبری داخل ان پی ان کلا کار نمیکنه آپدیت نیست
پیام رسان شما حتی قادر نیست تشخیص بده توکنی که بهش دادی کار میکنه یا خیر
صدر رحمت به بله باز یه مثال داغون داره داکیومنتشن های اصن معلوم نیست چی گفتین

و  حدسم این هستش که این پیام پاک میشه
اگر واقعا ادعا دارید پاسخگو باشید

پشتبانیتونم که کشکه هیچ پاسخی نمیده

**Comment by A1Gard** [comment]
اینم آرشیو کردم تو 
web
تا اگر به سرتون از پاک کنین 

تا تو بوق و کرنا کنمش
امیدوارم با پاسخگویتنون منو شرمنده کنین

https://web.archive.org/web/20180526215755/https://github.com/GapAfzar/Node-Gap-SDP-API/issues/4

اینم از اتفضاح 
npm
بعد از تست
https://runkit.com/embed/a49s9yfp13mu

**Comment by mehdijamal** [comment]
ورژن لایبرری در 
npm 
آپدیت نبود 
لطفا بعد از آپدیت اگر به مشکلی برخوردید مجددا پیگیری بفرمایید

**Comment by A1Gard** [comment]
این آپدیت کی انجام میشود؟

**Comment by mehdijamal** [comment]
@A1Gard 
آپدیت انجام شده 
منظورم این بود که مجددا لایبرری gap_api رو نصب کنید

**Comment by A1Gard** [comment]
کد من:
@mehdijamal 
```

"use strict";

var GapApi = require('gap_api');
var gap = new GapApi('my_token');
gap.onText('salam', (data) => {
	console.log('b', data);
});

try {
    gap.sendText('chat_id', 'salam', [
        [
            {"OK" : 'OK'}
        ],
    ]);
    gap.sendImage('chat_id', './ali.jpg', 'desc', [
        [
            {"OK" : 'OK'}
        ],
    ]);
    gap.sendVideo('chat_id', './test.mp4', 'desc video', [
        [
            {"OK" : 'OK'}
        ],
    ]);
} catch(e) {
    console.log(e);
}
 
```

Error :

(node:6951) UnhandledPromiseRejectionWarning: an error was encountered
(node:6951) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6951) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

 و کار نمیکنه

خواهش میکنم یه مثال درست و درمون بذارید ازش
